#!/usr/bin/env python
import argparse
import os
from sys import version_info

assert version_info >= (3, 4)

CWD = os.getcwd()

try:
    from chomikuploader.main import Main, setup_logger
except ImportError:
    from src.main import Main, setup_logger

if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    parser.add_argument(
        '-v', '--verbose', action='store_true',
        help='Wyświetla więcej komunikatów z działania programu'
    )
    parser.add_argument(
        '-t', '--threads', default=1,
        help='Liczba wątków (ilość plików wysyłanych jednocześnie)'
    )
    parser.add_argument(
        '-l', '--login',
        help='Nazwa/login chomika'
    )
    parser.add_argument(
        '-p', '--password', metavar='HASŁO', 
        help='Hasło chomika'
    )

    parser.add_argument(
        'source', metavar='SCIEZKA_LOKALNA',
        help='Ścieżka do pliku lub katalogu na komputerze'
    )

    parser.add_argument(
        'destination', metavar='KATALOG_W_CHOMIKU',
        help='Docelowy katalog na chomiku'
    )

    kwargs = parser.parse_args()
    logger = setup_logger(kwargs.verbose)

    main = Main(cwd=CWD, logger=logger, **kwargs.__dict__)
    main.upload()
