#!/usr/bin/env python
import argparse
import os
from sys import version_info

assert version_info >= (3, 4)

CWD = os.getcwd()

try:
    from chomikuploader.main import Main
except ImportError:
    from src.main import Main


def setup_logger(verbose=False):
    import logging
    import sys

    logger_format = '%(asctime)s [%(levelname)s] %(message)s'
    logger = logging.getLogger('chomik')
    logger.setLevel(logging.DEBUG)
    logger.propagate = False

    if verbose:
        logger_handler = logging.StreamHandler(stream=sys.stdout)
        logger_handler.setLevel(logging.DEBUG)
        logger_handler.setFormatter(logging.Formatter(logger_format))
    else:
        debug_handler = logging.NullHandler(level=logging.DEBUG)
        logger.addHandler(debug_handler)

        logger_handler = logging.StreamHandler(stream=sys.stdout)
        logger_handler.setLevel(logging.INFO)
        logger_handler.setFormatter(logging.Formatter(logger_format))

    logger.addHandler(logger_handler)

    return logger


if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    parser.add_argument(
        '-v', '--verbose', action='store_true',
        help='Wyświetla więcej komunikatów z działania programu'
    )
    parser.add_argument(
        '-l', '--login',
        help='Nazwa/login chomika'
    )
    parser.add_argument(
        '-p', '--password', metavar='HASŁO', 
        help='Hasło chomika'
    )

    parser.add_argument(
        'source', metavar='SCIEZKA_LOKALNA',
        help='Ścieżka do pliku lub katalogu na komputerze'
    )

    parser.add_argument(
        'destination', metavar='KATALOG_W_CHOMIKU',
        help='Docelowy katalog na chomiku'
    )

    kwargs = parser.parse_args()
    logger = setup_logger(kwargs.verbose)

    main = Main(cwd=CWD, logger=logger, **kwargs.__dict__)
    main.upload()
